development:
  adapter: sqlite3
  database: db/mockserver.db
  pool: 5
  timeout: 5000

migration:
  adapter: sqlite3
  database: ../mockserver.db
  pool: 5
  timeout: 5000

example_mysql:
  adapter: mysql2
  encoding: utf8
  database: my_db_name
  username: root
  password: my_password
  host: 127.0.0.1
  port: 3306

test:
  adapter: sqlite3
  database: db/mockserver_test.db
  pool: 5
  timeout: 5000

development_pg:
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password: postgres
  host: localhost

development_docker:
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password: postgres
  host: pg_database
